### PR TITLE
upgrade from packed_smid to `core::simd`

### PR DESCRIPTION
**Pull request by wzh4464**
1. SMID Fixes
Reason: Rust has integrated some SMID functions into the standard core library, eliminating the need for the platform-intrinsic feature. The previous packed_smid was rendered unusable, so it has been transitioned to be compatible with the core library.
2. Test Case Order Fixes
Addressed issues caused by the order of execution affecting test cases.
3. Dependency Updates
Updated dependencies to their latest versions for enhanced functionality and security.

### CODE REVIEW

**Comment by wzh4464** [comment]
I have run the test. Except the minibatch all are passed. For minibatch, maybe it is potentially due to a stochastic issue?

**Comment by seijikun** [comment]
I modified your commits a bit by:
- Removing the styling changes so the commit is more smaller (will run formatter in extra commit)
- Squashing the commit that fixes warnings into the porting commit
- Skipping the commit that fixes the failing tests - I've got an idea for a more permanent solution
- Getting rid of the merge commit for a cleaner commit history

I kept your commits in your name though.
Thank you very much!

**Comment by wzh4464** [comment]
Very happy to have contributions to the repo!
Thank you very much!

**Comment by seijikun** [comment]
I just released a new version (`v0.10.0`) containing your changes to crates.io.
Thanks again!

**Pull request merged**
